dist: trusty
sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox

before_install:
  - pip install coveralls

after_success:
  - tox -e coverage-report
  - coveralls
